from aenum import Enum, NoAlias


class Extension(Enum, settings=NoAlias):
    """
        File extensions handled and there associated folder names.
    """
    PDF = 'pdf'
    TXT = 'text'
    DOCX = 'word'
    PNG = 'images'
    JPG = 'images'
    ZIP = 'zipped'
    SH = 'scripts'
    GZ = 'zipped'
    CSV = 'csv-excel'
    XLSX = 'csv-excel'
    XLSM = 'csv-excel'
    HTML = 'web-page'
    JSON = 'json'
    EXE = 'applications'
    APP = 'applications'
    DMG = 'applications'
    PKG = 'applications'
    ISO = 'iso-image'
    OVA = 'os-image'
    JS = 'java-script'
    JAVA = 'java-app'
    CLASS = 'java-class'
    PYC = 'python-app'
    XML = 'xml'
    SVG = 'vectors'
    CER = 'certificates'
    CERT = 'certificates'
    CRT = 'certificates'
    PEM = 'certificates'
    KEY = 'certificate-keys'
    P12 = 'key-pairs'
    GIF = 'gifs'
    JKS = 'jks'
    RLC = 'rhapsody'
    UNKNOWN = 'misc'
